# Generated by Django 3.2.9 on 2023-02-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_image',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
