# Generated by Django 4.2.11 on 2024-03-24 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
