# Generated by Django 5.0.2 on 2024-03-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_product_sizes_size_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ref',
            new_name='id',
        ),
    ]
