# Generated by Django 3.2.9 on 2023-02-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_variant_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountDetail',
            new_name='Account',
        ),
    ]
