# Generated by Django 3.2.9 on 2023-02-19 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230217_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='api.brand'),
        ),
    ]
