# Generated by Django 5.0.2 on 2024-03-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, to='api.orderitem'),
        ),
    ]
