# Generated by Django 3.2.9 on 2023-02-20 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='api.variant'),
        ),
    ]
