# Generated by Django 3.2.9 on 2023-03-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_size_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
