# Generated by Django 5.0.2 on 2024-03-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cart_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='owner',
            new_name='user',
        ),
    ]
