# Generated by Django 3.2.9 on 2023-03-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20230303_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='image_url',
            field=models.URLField(),
        ),
    ]
